<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My medical history application</title>
</head>
<body>
    <div style="margin-top: 10px">Greetings, ${name}</div>
    <div>Good day <b>${name}</b></div>

    <br/>
    <div>We are pleased to inform you that your appointment has successfully been booked</div>
    <div> Have a nice day..!</div>
</body>
</html>