<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My medical history application</title>
</head>
<body>
    <div style="margin-top: 10px">Greetings, ${name}</div>
    <br/>
    <div>We are pleased to inform you that your appointment has successfully been booked</div>
    <div>Below are the details</div>
    <div>Date: ${date}</div>
    <div>Time: ${time}</div>
    <div>Duration: ${duration}</div>
    <div>Doctor:  ${doctor}</div>
    <br/>
    <div>We are looking forward to seeing you at Lota Medical Center</div>1
</body>
</html>