<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My medical history application</title>
</head>
<body>
    <div style="margin-top: 10px">Greetings, ${name}</div>
    <br/>
    <div>You have a new appointment on your desk</div>
    <div>Below are the details</div>
    <div>Date: ${date} </div>
    <div>Time: ${time} </div>
    <div>Duration: ${duration} </div>
    <div>Patient name:  ${patientName} </div>
    <div>Patient Id:  ${patientId} </div>
    <br/>
    <div>Thank you once again for your wonderful service to our patients</div>
</body>
</html>