<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My medical history application</title>
</head>
<body>
    <div style="margin-top: 10px">Greetings, ${name}</div>
    <div>Welcome to Lota Medical Center</div>
    <div>Your username is <b>${name}</b></div>
    <div>Please confirm your email <b>${token}</b></div>
    <br/>
    <div>It works, their father</div>
    <div> Have a nice day..!</div>
</body>
</html>